### PR TITLE
Fix notifications appearing when Element is iframed

### LINKED ISSUE #16860: Dialog for Desktop Notifications should not appear when riot is inside an iframe
I'll send a Pull Request for your evaluation. 

The proposal is quite simple: only return `true` in `WebPlatform.supportsNotification()` if riot web is the top page, so that it will not appear when inside an iframe.

### PR DESCRIPTION
**Pull request by dtygel**
Fixes #16860

### CODE REVIEW

**Comment by SimonBrandner** [comment]
@dtygel, thanks for working on this! Could you please include a sign-off as described [here](https://github.com/matrix-org/matrix-js-sdk/blob/develop/CONTRIBUTING.rst#sign-off) and rename the PR to explain what it does (we use PR names to generate the changelogs)? The CI is failing because your branch seems to be out of date. Could you please fix that too?

**Comment by turt2live** [comment]
The change looks reasonable from a code perspective, however we need some justification for why we'd want this. Before I'd be comfortable sending this off to product review I'd like to have more information about why this feature is required, and what use cases would benefit from it.

Also, if you get the chance, please rebase out the multiple merge commits and other unrelated changes.

**Comment by t3chguy** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API/Using_the_Notifications_API

Because a cross-origin iframe can no longer do so;

> In addition, In Chrome and Firefox you cannot request notifications at all unless the site is a secure context (i.e. HTTPS), and you can no longer allow notification permissions to be requested from cross-origin <iframe>s.

But I would argue the PR here is a bit too strict and should only disable the prompt when the parent is cross-origin

**Comment by SimonBrandner** [comment]
There hasn't been any activity here for quite a while. @dtygel, do you plan to continue to work on this PR?

**Review by rohith5112 — CHANGES_REQUESTED** [review]
need more info

**Comment by SimonBrandner** [comment]
I will close this as there doesn't seem to be a response from the author. _Feel free_ to reopen or ping me if this is still a problem.

**Pull request closed without merging**
