### PR TITLE
Deleted text shouldn't have share capability

### LINKED ISSUE #21785: Deleted text shouldn't have share capability
#### What would you like to do?
I realized if a message is deleted, it stays in the chat space as deleted, also it can be shared as shown in the image below:

Capture2

I'll suggest after a chat is deleted each user should be able to delete it entirely from their chat space, `delete/remove` should replace the `share` option as shown in the image above.

#### Why would you like to do it?

For cleaner chat space and better user experience

#### How would you like to achieve it?
Needs inputs from the team, probably i can start working on it based on their guidance and suggestion.

### Have you considered any alternatives?

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by asaayushisingh**
Fixes #21785 
You can compare the PR at the link given below
https://github.com/asaayushisingh/matrix-react-sdk
with the currently deployed codes of [matrix-react-sdk](https://github.com/matrix-org/matrix-react-sdk) repository

### **Problem**
 If a message is deleted, it stays in the chat space as deleted, also it can be shared as shown in the image below:

**Before--->**

https://user-images.githubusercontent.com/67657066/163726454-5e012030-f75f-4f67-9296-8bfcd1cbfc3a.mp4

**After--->**

https://user-images.githubusercontent.com/67657066/163726404-094c1d32-ede3-4e1c-bfd9-d069b2b01b7e.mp4

---
This PR currently has no changelog labels, so will not be included in changelogs.

A reviewer can add one of: `T-Deprecation`, `T-Enhancement`, `T-Defect`, `T-Task` to indicate what type of change this is, or add `Type: [enhancement/defect/task]` to the description and I'll add them for you.

### CODE REVIEW

**Comment by asaayushisingh** [comment]
Hey! @turt2live Kindly review this PR.  Thank You!

**Review by turt2live — CHANGES_REQUESTED** [review]
I think your PR is at the wrong layer - there's 10k commits and 380k lines changed.

**Comment by asaayushisingh** [comment]
Hey! @turt2live, I am a bit confused between the various repositories under this project. Since I made particular changes in [matrix-react-sdk](https://github.com/matrix-org/matrix-react-sdk) repository. So if I am not wrong then I think that you can compare my contributed branch(https://github.com/asaayushisingh/matrix-react-sdk/tree/remove-share-button-%2321785) with the production branch at that particular repository(https://github.com/asaayushisingh/matrix-react-sdk).
May I know where I am getting wrong?

**Comment by robintown** [comment]
Right, so if the changes you made were against the matrix-react-sdk repository, you should re-submit your PR at https://github.com/matrix-org/matrix-react-sdk/compare rather than here.

**Pull request closed without merging**
