### PR TITLE
element.io defaults for sign in with QR

### PR DESCRIPTION
**Pull request by hughns**
Proposed behaviour:

app.element.io
==
- enable showing QR from settings where homeserver supports it
- no fallback server

**Login screens:**

No change to login screens.

**Settings screens:**

If the homeserver doesn't have the support for QR login enabled then settings will look no different from normal:

image

However, if QR login is enabled on the homeserver (support for MSC3882 and MSC3886) then it would look like this:

image

develop.element.io
==

- enable showing QR at point of login
- enable showing and scanning QR from settings where homeserver supports it
- fallback server configured for when HS doesn't have MSC3886 enabled

**Login screens:**

So, at login a new button is visible:

image

**Settings screens:**

If the homeserver doesn't support MSC3882 then it will look like normal:

image

If the homesever does support MSC3882 then it will look like this:

image

## Checklist

* [ ] Tests written for new code (and old code if feasible)
* [ ] Linter and other CI checks pass
* [ ] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/vector-im/element-web/blob/develop/CONTRIBUTING.md))

---
Here's what your changelog entry will look like:

## ✨ Features
 * element.io defaults for sign in with QR ([\#23491](https://github.com/vector-im/element-web/pull/23491)). Contributed by @hughns.

### CODE REVIEW

**Comment by t3chguy** [comment]
Needs similar PR for Element Desktop configs - https://github.com/vector-im/element-desktop/

**Comment by t3chguy** [comment]
Given this is touching release instances it should get a product checkmark

**Comment by hughns** [comment]
The plan is that once other parts of the QR login are more widely available (e.g. server support, better support in iOS/Android), additional capabilities would be opened up on app.element.io.

**Review by turt2live — COMMENTED** [review]
Clearing code review while in draft

(also don't forget about element-desktop)

**Comment by hughns** [comment]
I'm closing this as rollout is taking a different approach via https://github.com/matrix-org/matrix-react-sdk/pull/10066

**Pull request closed without merging**
