### PR TITLE
Fix frame-ancestors docs from none to self to not break Jitsi

### PR DESCRIPTION
**Pull request by t3chguy**
Fixes https://github.com/vector-im/element-web/issues/21095

---
This change is marked as an *internal change* (Task), so will not be included in the changelog.

### CODE REVIEW

**Review by turt2live — DISMISSED** [review]
I'm a bit concerned this allows Element itself to be embedded in an iframe, thus introducing security risk by way of clickjacking. 

From what I understand, we should be changing the CSP headers depending on the resource, as we did at some point in the past for user content.

It might also be good to get security review for this in addition to code review.

**Comment by t3chguy** [comment]
It's only allowing itself to be iframed by itself

**Comment by bwindels** [comment]
@turt2live @t3chguy This PR seems to have stalled, you think this can be merged?

**Comment by turt2live** [comment]
I think this needs security review before it can go forward.

**Comment by nodiscc** [comment]
> I think this needs security review before it can go forward.

Any updates on this? I can confirm that this fixes https://github.com/vector-im/element-web/issues/21095 for me, and as @t3chguy puts it, It's only allowing itself to be iframed by itself, so I think the security implications are low.

**Review by davidegirardi — APPROVED** [review]

**Review by andybalaam — APPROVED** [review]

**Pull request merged**
