### PR TITLE
Spaces keyboard shortcuts first cut

### PR DESCRIPTION
**Pull request by t3chguy**
Requires https://github.com/matrix-org/matrix-react-sdk/pull/6088
Towards https://github.com/vector-im/element-web/issues/17128

image

### CODE REVIEW

**Review by jryans — APPROVED** [review]
Seems okay to try as long as it's desktop only. Should Product review as well?

**Comment by t3chguy** [comment]
It was instigated by Nad but sure, not in any rush for it to land

**Review by nadonomy — APPROVED** [review]

**Review by nadonomy — CHANGES_REQUESTED** [review]
Actually sorry, @t3chguy is it trivial to make 0 act as Home/all instead? and then 1-9 for Spaces?

**Comment by t3chguy** [comment]
@nadonomy sure, even more trivial than the implementation I have but wouldn't it feel weird for them to be in a different order?

On screen they'd be

Home, Space 1, Space 2, etc
on keyboard they'd be
Space 1, Space 2, Space 3, ... Space 9, Home

**Comment by nadonomy** [comment]
> @nadonomy sure, even more trivial than the implementation I have but wouldn't it feel weird for them to be in a different order?

I see the concern, but I don't think the keyboard shortcuts need to have as binary a relationship to the list. For example, in Figma 1-9 are for docs, skipping 'Home' entirely:

Screenshot 2021-06-17 at 12 23 58

I'd rather start here to test that first, as I'm also thinking ahead on further visual iteration and interactions we'll do on the space panel in future. It'll be tough to change if people build muscle memory which isn't congruent with the overall direction.

Can we start here first, and iterate? Or perhaps throw in a labs flag with this as the default but allow us to dogfood both internally/in the beta?

**Review by nadonomy — APPROVED** [review]

**Pull request merged**
