### PR TITLE
Updated the login logo.

### PR DESCRIPTION
**Pull request by ankur12-1610**
Signed-off-by: ankur12-1610 <anknerd.12@gmail.com>

Fixes: #20785 

Before:
151393234-d0e4ef5b-b2d1-4d23-becd-8747955a04cc

After:

logochange

---
This change has no change notes, so will not be included in the changelog.

### CODE REVIEW

**Comment by ankur12-1610** [comment]
@nadonomy could you please review :sweat_smile: ?

**Review by SimonBrandner — COMMENTED** [review]
Just to check - have you made sure the logo isn't used elsewhere, so that we don't change it in the wrong places?

**Comment by ankur12-1610** [comment]
> Just to check - have you made sure the logo isn't used elsewhere, so that we don't change it in the wrong places? 

Yeah, I checked it and I only found `element-logo.svg` in `res/themes/element/img/logos` and in the web app which is generated in the build. So I just replaced the previous logo with the new one.

**Review by gsouquet — APPROVED** [review]
`element-logo.svg` is referenced in 4 components

- `CompabilityView.tsx`
- `ErrorView.tsx`
- `VectorAuthHeaderLogo.tsx`
- `HomePage.tsx`

To facilitate the review from the deisgn team, could you attach screenshots of those instances in the PR?
Code otherwise looks good

**Comment by ankur12-1610** [comment]
> `element-logo.svg` is referenced in 4 components
> 
> * `CompabilityView.tsx`
> * `ErrorView.tsx`
> * `VectorAuthHeaderLogo.tsx`
> * `HomePage.tsx`
> 
> To facilitate the review from the deisgn team, could you attach screenshots of those instances in the PR? Code otherwise looks good

@gsouquet  those instances, in the sense the code snippet?

**Comment by gsouquet** [comment]
No, taking screenshots of how they look in the product

**Comment by ankur12-1610** [comment]
> No, taking screenshots of how they look in the product

Oh! got it I'll upload them :)

**Comment by ankur12-1610** [comment]
> * CompabilityView

homepage

home



error


logochange

**Comment by ankur12-1610** [comment]
@gsouquet could you please check?
I'm unsure about the 'paths` :sweat_smile:.

**Comment by ankur12-1610** [comment]
> @gsouquet could you please check? I'm unsure about the 'paths` sweat_smile.

I also changed `res/welcome/images/logo.svg` as it had previous logo.

**Comment by ankur12-1610** [comment]
@gsouquet sorry to disturb but can you review the current changes:sweat_smile:

**Comment by SimonBrandner** [comment]
> @gsouquet sorry to disturb but can you review the current changessweat_smile

@gsouquet has already reviewed your PR. Now the PR is awaiting a review from the design team

**Review by AstroOrbis — APPROVED** [review]

**Comment by ankur12-1610** [comment]
> > @gsouquet sorry to disturb but can you review the current changessweat_smile
> 
> @gsouquet has already reviewed your PR. Now the PR is awaiting a review from the design team

Actually, I changed one more file, so I just needed confirmation for that :')

Design team gave an approval :tada:

**Comment by SimonBrandner** [comment]
> > > @gsouquet sorry to disturb but can you review the current changessweat_smile
> > 
> > 
> > @gsouquet has already reviewed your PR. Now the PR is awaiting a review from the design team
> 
> Actually, I changed one more file, so I just needed confirmation for that :')
> 
> I guess, design team gave an approval tada

I am afraid @AstroOrbis isn't a member of the design team :(

**Comment by AstroOrbis** [comment]
I'm not haha, I just find the change cool :3 👍🏻

**Comment by ankur12-1610** [comment]
> I'm not haha, I just find the change cool :3 👍🏻 

xD

**Comment by ankur12-1610** [comment]
> > > > @gsouquet sorry to disturb but can you review the current changessweat_smile
> > > 
> > > 
> > > @gsouquet has already reviewed your PR. Now the PR is awaiting a review from the design team
> > 
> > Actually, I changed one more file, so I just needed confirmation for that :')
> > 
> > I guess, design team gave an approval tada
> 
> I am afraid @AstroOrbis isn't a member of the design team :(

😥At what frequency does the design team review the PRS?

**Comment by SimonBrandner** [comment]
> > > > > @gsouquet sorry to disturb but can you review the current changessweat_smile
> > > > 
> > > > 
> > > > @gsouquet has already reviewed your PR. Now the PR is awaiting a review from the design team
> > > 
> > > 
> > > Actually, I changed one more file, so I just needed confirmation for that :')
> > > I guess, design team gave an approval tada
> > 
> > 
> > I am afraid @AstroOrbis isn't a member of the design team :(
> 
> disappointed_relievedAt what frequency does the design team review the PRS?

It very much depends, often longer time than the code review as the design team is often busy.

@nadonomy, do you want to take a look, as you're the author of the issue?

**Comment by ankur12-1610** [comment]
Ah! get it, np :)

**Review by JordanConnor — APPROVED** [review]
Looks good to me 👍

**Pull request merged**
