### PR TITLE
Add example for deployment into Kubernetes

### PR DESCRIPTION
**Pull request by nielsbasjes**
This is the cleaned version of kubernetes config I use to run it in my own environment.
It simply shows users how they can get it running and how to get the config operational in a way that works.

This is intended as a basic "getting started" example.

### CODE REVIEW

**Review by jryans — CHANGES_REQUESTED** [review]
Thanks for the contribution!

I am somewhat reluctant to accept this because it won't be maintained by the core team... but perhaps there's still some value for others. I don't think it's appropriate as a file in root of the repo at least.

One option might be add a `kubernetes.md` to the docs folder, and that could have some inline config blocks. You could link to that from the README.

Another option would be linking to a separate repo or blog post about how to configure things for Kubernetes.

**Comment by nielsbasjes** [comment]
I'll make it a documentation thing.

**Comment by nielsbasjes** [comment]
@jryans Is this what you had in mind?

**Review by jryans — APPROVED** [review]
Indeed, thanks, this seems good to me! 😄

**Pull request merged**
