### PR TITLE
Update apple-app-site-association

### PR DESCRIPTION
**Pull request by t3chguy**
Fixes https://github.com/vector-im/element-web/issues/24844

---
This change is marked as an *internal change* (Task), so will not be included in the changelog.

### CODE REVIEW

**Comment by t3chguy** [comment]
`develop.element.io/apple-app-site-association` will be updated by CD
`{staging,app}.element.io/apple-app-site-association` will be updated by @andybalaam next week and the week after respectively as part of the release process
`riot.im/{staging,app}` will mirror behaviour of `{staging,app}.element.io` above
`riot.im/develop/apple-app-site-association` will be deployed manually by myself once this PR merges

**Review by gsouquet — APPROVED** [review]

**Comment by Johennes** [comment]
> `develop.element.io/apple-app-site-association` will be updated by CD
> [...]
> `riot.im/develop/apple-app-site-association` will be deployed manually by myself once this PR merges

Could / should we integrate the riot.im deployment with CD as well?

**Comment by andybalaam** [comment]
> `develop.element.io/apple-app-site-association` will be updated by CD `{staging,app}.element.io/apple-app-site-association` will be updated by @andybalaam next week and the week after respectively as part of the release process `riot.im/{staging,app}` will mirror behaviour of `{staging,app}.element.io` above `riot.im/develop/apple-app-site-association` will be deployed manually by myself once this PR merges

Will this require me to do anything, or will it be automatic as part of the release process?

**Comment by t3chguy** [comment]
> Could / should we integrate the riot.im deployment with CD as well in future?

Nope as riot.im points to athena which cannot be the target of our GHA CI/CD infrastructure due to our security stance, and Cloudflare pages cannot be used to host a subpath, only a subdomain. riot.im/develop has been sunset and no longer receives updates as per the prominent toast on that deployment.

> or will it be automatic as part of the release process?

This

**Comment by t3chguy** [comment]
CD deployed to develop.e.io, manually deployed to riot.im/develop

```
t3chguy@t3chguy-MacBook-Pro ~> curl https://riot.im/develop/apple-app-site-association
{
    "applinks": {
        "apps": [],
        "details": [
            {
                "appID": "7J4U792NQT.im.vector.app",
                "paths": [
                    "*"
                ]
            }
        ]
    },
    "webcredentials": {
        "apps": [
            "7J4U792NQT.im.vector.app"
        ]
    }
}
t3chguy@t3chguy-MacBook-Pro ~> curl https://develop.element.io/apple-app-site-association
{
    "applinks": {
        "apps": [],
        "details": [
            {
                "appIDs":[
                    "7J4U792NQT.im.vector.app",
                    "7J4U792NQT.io.element.elementx",
                    "7J4U792NQT.io.element.elementx.nightly",
                    "7J4U792NQT.io.element.elementx.pr"
                ],
                "paths": [
                    "*"
                ]
            }
        ]
    },
    "webcredentials": {
        "apps": [
            "7J4U792NQT.im.vector.app",
            "7J4U792NQT.io.element.elementx",
            "7J4U792NQT.io.element.elementx.nightly",
            "7J4U792NQT.io.element.elementx.pr"
        ]
    }
}
t3chguy@t3chguy-MacBook-Pro ~> curl https://riot.im/develop/apple-app-site-association
{
    "applinks": {
        "apps": [],
        "details": [
            {
                "appIDs":[
                    "7J4U792NQT.im.vector.app",
                    "7J4U792NQT.io.element.elementx",
                    "7J4U792NQT.io.element.elementx.nightly",
                    "7J4U792NQT.io.element.elementx.pr"
                ],
                "paths": [
                    "*"
                ]
            }
        ]
    },
    "webcredentials": {
        "apps": [
            "7J4U792NQT.im.vector.app",
            "7J4U792NQT.io.element.elementx",
            "7J4U792NQT.io.element.elementx.nightly",
            "7J4U792NQT.io.element.elementx.pr"
        ]
    }
}
```

**Pull request merged**
