### PR TITLE
Update labs.md for knock rooms

### PR DESCRIPTION
**Pull request by charlynguyen**
We @nordeck are currently implementing the knock rooms behind the feature flag `feature_ask_to_join` (introduced in https://github.com/matrix-org/matrix-react-sdk/pull/11182).

This pull request updates the labs.md for knock rooms.

#### Relates to

- https://github.com/matrix-org/matrix-react-sdk/pull/11353
  - https://github.com/matrix-org/matrix-js-sdk/pull/3647
- https://github.com/matrix-org/matrix-react-sdk/pull/11248
- https://github.com/matrix-org/matrix-react-sdk/pull/11182

## Checklist

-   [ ] Tests written for new code (and old code if feasible)
-   [ ] Linter and other CI checks pass
-   [x] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/vector-im/element-web/blob/develop/CONTRIBUTING.md))

---
Here's what your changelog entry will look like:

## ✨ Features
 * Update labs.md for knock rooms ([\#25923](https://github.com/vector-im/element-web/pull/25923)). Contributed by @charlynguyen.

### CODE REVIEW

**Review by germain-gg — APPROVED** [review]

**Comment by catfromplan9** [comment]
When feature_ask_to_join is enabled in labs, I still don't see the "People" tab in room settings. How to fix?

**Comment by t3chguy** [comment]
@catfromplan9 did you set the rooms join rule to knock/ask to join first..?

**Comment by catfromplan9** [comment]
> @catfromplan9 did you set the rooms join rule to knock/ask to join first..?

Yes, and i requested to join on my alt. Im not seeing the request but i can use my instance to request to join rooms with that setting

**Comment by catfromplan9** [comment]
> > @catfromplan9 did you set the rooms join rule to knock/ask to join first..?
> 
> Yes, and i requested to join on my alt. Im not seeing the request but i can use my instance to request to join rooms with that setting

I deployed latest element from develop branch today. I have the ask to join function itself, just not the tab for accepting invites. develop.element.io works though

**Comment by t3chguy** [comment]
@catfromplan9 if it works on develop.element.io but not on your custom develop branch deployment then the issue sounds on your end. Keep in mind the feature only merged 2 days ago so definitely won't be in any release tags. https://github.com/vector-im/element-web/blob/develop/.github/workflows/build_develop.yml for how develop is built & deployed.

**Comment by catfromplan9** [comment]
> @catfromplan9 if it works on develop.element.io but not on your custom develop branch deployment then the issue sounds on your end. Keep in mind the feature only merged 2 days ago so definitely won't be in any release tags. https://github.com/vector-im/element-web/blob/develop/.github/workflows/build_develop.yml for how develop is built & deployed.

I ran this
```
git clone https://github.com/vector-im/element-web
cd element-web
yarn
yarn install
yarn dist
```
Then i untarred it in my webroot, and set the following settings (atleast the ones relevant to this issue) in my config.json
```
"showLabsSettings": true,
    "features": {
        "feature_many_integration_managers": "labs",
        "feature_pinning": "enable",
        "feature_html_topic": "labs",
        "feature_new_room_decoration_ui": "labs",
        "feature_custom_status": "enable",
        "feature_custom_tags": "labs",
        "feature_state_counters": "labs",
        "feature_custom_themes": "enable",
        "feature_bridge_state": "enable",
        "feature_mjolnir": "enable",
        "feature_ask_to_join": "enable",
        "feature_presence_in_room_list": "labs",
        "feature_roomlist_preview_reactions_all": "labs",
        "feature_roomlist_preview_reactions_dms": "labs",
        "feature_dm_verification": "labs",
        "feature_latex_maths": "labs",
        "feature_dehydration": "labs",
        "feature_report_to_moderators": "labs",
        "feature_hidden_read_receipts": "labs",
        "feature_polls": "enable",
        "feature_location_share_pin_drop": "labs",
        "feature_location_share_live": "labs",
        "feature_breadcrumbs_v2": "labs",
        "feature_spotlight": "labs",
        "feature_jump_to_date": "enable",
        "feature_voice_rooms": "enable",
        "feature_extensible_events": "labs"
    },
```

**Pull request merged**
