### PR TITLE
Add `default_server_config` fallback to element.io configs

### PR DESCRIPTION
**Pull request by aaronraimist**
This doesn't solve https://github.com/vector-im/element-web/issues/11154 but at least prevents it from happening on app.element.io and develop.element.io. `default_server_name` is also deprecated.

This PR greatly improves the user experience when matrix.org is unreachable. Currently it looks like this:

The error message doesn't provide much information about what went wrong and there is no way to switch to another server.

After this PR:

The error message actually says something meaningful and the user is able to switch to another server.

I will create a PR for desktop if this is acceptable.

---
This change is marked as an *internal change* (Task), so will not be included in the changelog.

### CODE REVIEW

**Comment by aaronraimist** [comment]
The only downside to this is the full base_url will be displayed on the login/registration screens rather than the server name. The documentation claims `default_server_config` supports specifying "a server_name under the m.homeserver section to display a custom homeserver name." however it doesn't actually work.

https://github.com/aaronraimist/matrix-js-sdk/commit/0303c9bc06a3b26f0f3d800de9b3b3d8063a3924 would make it work however there wouldn't be any validation of the server name so it could easily be used for phishing. I'm not quite sure how you could validate it. I suppose someone hosting an instance of Element already has to be trusted not to modify Element so that may not be a big deal.

**Comment by WestXu** [comment]
Been waiting for this for a long time.

**Review by turt2live — APPROVED** [review]
Thanks! What are the chances a similar change can be made to the element-desktop repository?

**Comment by aaronraimist** [comment]
@turt2live 100%. Do you want https://github.com/vector-im/element-web/pull/19695#issuecomment-966219350 as well?

**Comment by turt2live** [comment]
oh, hmm, didn't realize that this would cause the issue mentioned in that comment. I think instead we need to spend a bit of time to think about this, sorry.

**Comment by evan0greenup** [comment]
@t3chguy , Do you think this is ready to be approved?

**Comment by turt2live** [comment]
so in the end we've un-deprecated `default_server_name`, but it obviously doesn't solve the issue at hand regarding homeservers being offline. I am sort of wondering if it's something we need to fix though - it's managed to go a few years as an issue and hasn't seen much traction in terms of bug reporting. 

Curious to hear thoughts on the matter.

**Comment by aaronraimist** [comment]
@turt2live Personally I think it is a problem. I see it pop up in `#element-web:matrix.org` maybe once every 2 weeks, so it certainly isn't the biggest problem but it real.

I also think it is an under reported issue because if someone gets this error, there is absolutely nothing to suggest it is a problem on their your end. People likely just think: well the server is down, this sucks I'm going back to Discord/Slack/etc.

**Comment by ShadowRZ** [comment]
Is there anything blocking this PR from being merged?

**Comment by andybalaam** [comment]
We don't think we can merge this while it displays `matrix-client` on the front page. Would someone be willing to change the code to allow us to display `matrix.org` there, even when we provided this info?

**Comment by ShadowRZ** [comment]
在 2023-06-22 22:29，Andy Balaam 写道：
> We don't think we can merge this while it displays matrix-client on
> the front page. Would someone be willing to change the code to allow
> us to display matrix.org there, even when we provided this info?

Propose this:

1. If only `default_server_name` is provided, use well-known discovery 
and bails out if it fails (like before).
2. If only `default_server_config` is provided, use it only.
3. If both `default_server_config` and `default_server_name` is provided 
in the config, try well-known discovery first, it that fails, use the 
configuration in `default_server_config` instead. (More specially, use 
the content of `default_server_config` as a fallback discovery info).

Unfortunately I can't provide code that are tested because GFW blocks 
gitlab.matrix.org which is required to set up the dev environment and to 
test my code.

My draft patch:

```diff
  src/vector/app.tsx | 27 +++++++++++++++------------
  1 file changed, 15 insertions(+), 12 deletions(-)

diff --git a/src/vector/app.tsx b/src/vector/app.tsx
index 7371ccf0f..60a5e5a12 100644
--- a/src/vector/app.tsx
+++ b/src/vector/app.tsx
@@ -169,13 +169,6 @@ async function verifyServerConfig(): 
Promise<IConfigOptions> {
          const isUrl = config["default_is_url"];

          const incompatibleOptions = [wkConfig, serverName, 
hsUrl].filter((i) => !!i);
-        if (incompatibleOptions.length > 1) {
-            // noinspection ExceptionCaughtLocallyJS
-            throw new UserFriendlyError(
-                "Invalid configuration: can only specify one of 
default_server_config, default_server_name, " +
-                    "or default_hs_url.",
-            );
-        }
          if (incompatibleOptions.length < 1) {
              // noinspection ExceptionCaughtLocallyJS
              throw new UserFriendlyError("Invalid configuration: no 
default server specified.");
@@ -201,10 +194,6 @@ async function verifyServerConfig(): 
Promise<IConfigOptions> {
          }

          let discoveryResult: ClientConfig | undefined;
-        if (wkConfig) {
-            logger.log("Config uses a default_server_config - 
validating object");
-            discoveryResult = await 
AutoDiscovery.fromDiscoveryConfig(wkConfig);
-        }

          if (serverName) {
              logger.log("Config uses a default_server_name - doing 
.well-known lookup");
@@ -212,7 +201,21 @@ async function verifyServerConfig(): 
Promise<IConfigOptions> {
                  "DEPRECATED CONFIG OPTION: In the future, 
default_server_name will not be accepted. Please " +
                      "use default_server_config instead.",
              );
-            discoveryResult = await 
AutoDiscovery.findClientConfig(serverName);
+            try {
+                discoveryResult = await 
AutoDiscovery.findClientConfig(serverName);
+            } catch (e) {
+                if (wkConfig) {
+                    logger.log("default_server_config is avaliable - 
using it as a fallback");
+                    discoveryResult = await 
AutoDiscovery.fromDiscoveryConfig(wkConfig);
+                } else {
+                    throw e;
+                }
+            }
+        }
+
+        if (wkConfig && discoveryResult === undefined) {
+            logger.log("Config uses a default_server_config - 
validating object");
+            discoveryResult = await 
AutoDiscovery.fromDiscoveryConfig(wkConfig);
          }

          validatedConfig = 
AutoDiscoveryUtils.buildValidatedConfigFromDiscovery(serverName, 
discoveryResult, true);
```

**Comment by ShadowRZ** [comment]
My proposed patch can be found at [element-web.patch](https://github.com/vector-im/element-web/files/11902368/element-web.patch).

**Comment by andybalaam** [comment]
We discussed this last week and @t3chguy will work on getting this into mergeable state.

**Comment by t3chguy** [comment]
So the precursor to this is https://github.com/vector-im/element-web/pull/25682

**Comment by t3chguy** [comment]
Now that https://github.com/vector-im/element-web/pull/25682 has landed this PR no longer needs to remove the preferred `default_server_name`

**Review by t3chguy — APPROVED** [review]

**Pull request merged**
