### PR TITLE
Add `yarn start:https`

### PR DESCRIPTION
**Pull request by SimonBrandner**
FF and Chromium don't allow WebRTC without `https` if you're not connecting to `localhost` but sometimes you want to test WebRTC code with a different machine. This makes it possible

### CODE REVIEW

**Comment by t3chguy** [comment]
Doesn't webpack-dev-server by default forbid any non-local connections?

**Comment by SimonBrandner** [comment]
Hmm, this worked for me.. Maybe we have it disabled

**Comment by SimonBrandner** [comment]
Maybe we misunderstood each other. What did you mean by _non-local connections_? This should work only on LAN

**Comment by SimonBrandner** [comment]
Hmm, we should theoretically be able to use [this](https://stackoverflow.com/a/60458728/10822785) but I am having trouble to get it working at the moment

**Comment by SimonBrandner** [comment]
[Upon further inspection, it seems that this would only work with `npm`](https://stackoverflow.com/a/50862023/10822785). I am not sure what is the best path forwards here - does anyone else have any thoughts?

**Comment by t3chguy** [comment]
> Hmm, this worked for me.. Maybe we have it disabled

I meant this

image

where webpack rejects unknown Hostnames if they are not e.g localhost or specified in the `public` property of the webpack config.

**Comment by SimonBrandner** [comment]
> [Upon further inspection, it seems that this would only work with `npm`](https://stackoverflow.com/a/50862023/10822785). I am not sure what is the best path forwards here - does anyone else have any thoughts?

Unless there is a way to do this that I am missing, this PR seems to be the only way to do this

**Review by turt2live — APPROVED** [review]
sure :D

**Pull request merged**
