### PR TITLE
Jitsi requests 'requires_client' capability if auth token is provided

### PR DESCRIPTION
**Pull request by maheichyk**
Jitsi can be opened in a popup window but it cannot work there if auth token is provided (auth=openidtoken-jwt). In this case the widget API is not available and a warn message is written to the console: '"Expected to have an OpenID credential, cannot initialize widget"

jitsi_popup

This PR suggests to request `io.element.requires_client` capability if auth token is provided. In this case user cannot open jitsi in a popup (icon is no shown).

## Checklist

-   [ ] Tests written for new code (and old code if feasible)
-   [ ] Linter and other CI checks pass
-   [x] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/vector-im/element-web/blob/develop/CONTRIBUTING.md))

---
Here's what your changelog entry will look like:

## 🐛 Bug Fixes
 * Jitsi requests 'requires_client' capability if auth token is provided ([\#24294](https://github.com/vector-im/element-web/pull/24294)). Contributed by @maheichyk.

### CODE REVIEW

**Comment by maheichyk** [comment]
Signed-off-by: Mikhail Aheichyk [mikhail.aheichyk@nordeck.net](mailto:mikhail.aheichyk@nordeck.net)

**Review by dbkr — COMMENTED** [review]
Agreed this seems like the correct thing to do. One thing: the explanation you've given in the PR description is great — could this go in a comment in the code? It's really useful context.

**Comment by maheichyk** [comment]
sounds good, comment is added to the code

**Comment by andybalaam** [comment]
Double-checking - @dbkr will you review this or should I?

**Review by dbkr — APPROVED** [review]

**Pull request merged**
