### PR TITLE
Fix 1.7.34 release date in changelog

### PR DESCRIPTION
**Pull request by lnicola**

### CODE REVIEW

**Comment by SimonBrandner** [comment]
This looks like a bug in https://github.com/matrix-org/allchange. The date in the changelog seems to be the date of the first RC, I think.

CC @dbkr

**Comment by SimonBrandner** [comment]
Also, this should go to the release branch and develop branch

**Comment by lnicola** [comment]
Ugh, I edited the file in the GitHub editor, why didn't it pick `develop` as the default branch? Should I close this one? What's the difference between `master` and `develop`?

By the way, what happened in this release? It seems to have more changes than the last couple of releases together.

**Comment by lnicola** [comment]
Filed #18552 and #18553.

**Comment by SimonBrandner** [comment]
> Should I close this one?

Sorry, I wasn't completely clear, this should go to `master`, `develop`, `releasev-...`. 

> By the way, what happened in this release? It seems to have more changes than the last couple of releases together.

We started using a new changelog generator that actually lists all changes rather than just changes in the layer (we also have https://github.com/matrix-org/matrix-react-sdk and https://github.com/matrix-org/matrix-js-sdk/)

**Pull request closed without merging**
