### PR TITLE
Remove items incorrectly included in changelog for 1.11.24

### PR DESCRIPTION
**Pull request by andybalaam**
---
This change is marked as an *internal change* (Task), so will not be included in the changelog.

### CODE REVIEW

**Comment by richvdh** [comment]
Any context around this? How did the changelog end up with the wrong things?

**Comment by t3chguy** [comment]
Allchange wrongly adds things from develop when cutting >rc.1

**Comment by richvdh** [comment]
ugh, how annoying.

I'm not really sure what sort of review I'm meant to do here. It certainly removes some items from the changelog, but I don't know how to figure out if they are the right items.

The diff from v1.11.24-rc.2 is https://github.com/vector-im/element-web/compare/v1.11.24-rc.2...andybalaam/fix-release-notes-1.11.24#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4ed.

**Comment by andybalaam** [comment]
> I'm not really sure what sort of review I'm meant to do here. It certainly removes some items from the changelog, but I don't know how to figure out if they are the right items.

I'd suggest trusting me :-)

I opened each PR and checked its merge date. For PRs that were merged on the day of the RC or the day before or after, I found the commit in `git log` and then did `git tag --contains COMMITID` to check whether it was contained in the release commit.

**Review by richvdh — APPROVED** [review]

**Pull request merged**
