### PR TITLE
Updated workflow to check if unlabelled issue is in X-Needs-Info column

### PR DESCRIPTION
**Pull request by ankur12-1610**
Signed-off-by: ankur12-1610 <anknerd.12@gmail.com>

Fixes: #20476 

Updated workflow to check if the unlabelled issue is in the X-Needs-Info column.

---
This PR currently has no changelog labels, so will not be included in changelogs.

A reviewer can add one of: `T-Deprecation`, `T-Enhancement`, `T-Defect`, `T-Task` to indicate what type of change this is, or add `Type: [enhancement/defect/task]` to the description and I'll add them for you.

### CODE REVIEW

**Comment by ankur12-1610** [comment]
@kittykat I've updated the code but the testing is a little difficult, is there any other way to test it rather than creating new project and columns in the personal repo:cry:

Also, can you review the code?:sweat_smile:

**Comment by ankur12-1610** [comment]
> Could you link to the docs/example where you found `issue.column.name`?
> 
> I test on a private repo with the same projest setup - there aren't other easy ways to test, although palid mentioned [this repo](https://github.com/nektos/act) which may be some help

@kittykat I didn't find an exact command for checking the issue column, although I found this: https://docs.github.com/en/rest/reference/projects#get-a-project-column and did some changes in the GitHub API command, still not sure if it is going to work but this time I mentioned the endpoints correctly, if this doesn't work, I'll need to write a script and for that I need `column_id`, I think I don't have access to the `column_id`:sweat_smile:. 

If possible please test the code:smile:.

Sorry for the late reply, was sick for the past 3-4 days:cry:.

**Comment by ankur12-1610** [comment]
> Could you link to the docs/example where you found `issue.column.name`?
> 
> I test on a private repo with the same projest setup - there aren't other easy ways to test, although palid mentioned [this repo](https://github.com/nektos/act) which may be some help

Wow, this is an awesome repo, testing workflows locally, that's really great.
Thanks :)

**Comment by kittykat** [comment]
> for that I need `column_id`, I think I don't have access to the `column_id`sweat_smile.

I'll give it a go, but FYI, I think you should be able to get that out using the graphQL API and [explorer](https://docs.github.com/en/graphql/overview/explorer) as the project is public - you may need to authenticate though

> Sorry for the late reply, was sick for the past 3-4 dayscry.

I hope you feel better soon!

**Comment by ankur12-1610** [comment]
> > for that I need `column_id`, I think I don't have access to the `column_id`sweat_smile.
> 
> I'll give it a go, but FYI, I think you should be able to get that out using the graphQL API and [explorer](https://docs.github.com/en/graphql/overview/explorer) as the project is public - you may need to authenticate though
> 
> > Sorry for the late reply, was sick for the past 3-4 days:cry:.
> 
> I hope you feel better soon!

Got it :), thanks!

**Comment by ankur12-1610** [comment]
@kittykat did you test the code?:sweat_smile:

**Comment by kittykat** [comment]
> @kittykat did you test the code?sweat_smile

Not yet, I will get to it soon

**Comment by ankur12-1610** [comment]
> > @kittykat did you test the code?sweat_smile
> 
> Not yet, I will get to it soon

Np :)

**Comment by ankur12-1610** [comment]
> > @kittykat did you test the code?sweat_smile
> 
> Not yet, I will get to it soon

Did you check it? 😅

**Review by kittykat — CHANGES_REQUESTED** [review]
`github.event.project.columns.*.name` is all the columns in the project, so atm the check is whether "Needs info" is a column in the project so it always returns true

**Comment by ankur12-1610** [comment]
> `github.event.project.columns.*.name` is all the columns in the project, so atm the check is whether "Needs info" is a column in the project so it always returns true

Ah! got it, I need to do a bit more research and experimentation in it. @kittykat if you found something please share :sweat_smile:

**Comment by kittykat** [comment]
Hi @ankur12-1610, have you had a chance to take another look at this issue?

**Comment by ankur12-1610** [comment]
> Hi @ankur12-1610, have you had a chance to take another look at this issue?

Sorry @kittykat I didn't get the time to give it a try, I'll take a look at it in a week or two :sweat_smile:. But I'm positive that I'll solve this issue once I get back to it.

**Comment by t3chguy** [comment]
Abandoned - reopen if you are working on it.

**Pull request closed without merging**
