### PR TITLE
Document custom home view

### PR DESCRIPTION
**Pull request by johannes-krude**
This provides documentation for https://github.com/matrix-org/matrix-react-sdk/pull/7790 as well as some general information on configuring a custom home view.

The included example also depends on https://github.com/matrix-org/matrix-react-sdk/pull/7783.

Notes: Document how to configure a custom `home.html`.

Signed-off-by: Johannes Krude <johannes.krude@comsys.rwth-aachen.de>
Type: enhancement

---
Here's what your changelog entry will look like:

## ✨ Features
 * Document how to configure a custom `home.html`. ([\#21066](https://github.com/vector-im/element-web/pull/21066)). Contributed by @johannes-krude.

### CODE REVIEW

**Review by turt2live — APPROVED** [review]
documentation seems fine, pending product approval.

**Review by turt2live — CHANGES_REQUESTED** [review]
sorry, our config docs changed since this was reviewed. We'll need to link to this from the config.md part where it talks about this thing.

**Comment by johannes-krude** [comment]
Linked to this from `config.md` and adapted to the changes in https://github.com/matrix-org/matrix-react-sdk/pull/7790

**Review by turt2live — APPROVED** [review]
this will suffice for now - thanks!

**Pull request merged**
