### PR TITLE
minor string change in settings tab

### PR DESCRIPTION
**Pull request by aj-ya**
Fixes: #20755 

Signed-off-by: Ajeya Bhat <ajeyabhat.off@gmail.com>

Notes:
> Changed `... recently visited room or community`  to `... recently visited room or space`

---
This PR currently has no changelog labels, so will not be included in changelogs.

A reviewer can add one of: `T-Deprecation`, `T-Enhancement`, `T-Defect`, `T-Task` to indicate what type of change this is, or add `Type: [enhancement/defect/task]` to the description and I'll add them for you.

### CODE REVIEW

**Review by SimonBrandner — APPROVED** [review]
LGTM - thank you for working on this!

**Comment by t3chguy** [comment]
You can still switch to communities in Settings, unfortunately the string should vary depending on if the user has Spaces or Communities enabled
image

**Review by turt2live — COMMENTED** [review]
I'm inclined to keep this as-is until Communities are deleted, at which point we can consider the string (and fix it). 

I believe the deletion is planned Soon™, though don't have an exact target date just yet.

**Comment by aj-ya** [comment]
Hey @turt2live  !  If I'm not wrong, there aren't any more changes to be done to the solution right? If not, should I proceed  
with the below suggestion by @t3chguy 
> You can still switch to communities in Settings, unfortunately, the string should vary depending on if the user has Spaces or Communities enabled  image

P.S. apologies for the late reply, i thought the pr would be merged.

**Comment by luixxiul** [comment]
It looks like this PR reinserts the shortcuts moved to react-sdk with https://github.com/matrix-org/matrix-react-sdk/pull/7850/files#diff-454f7f431b8bcf5cfe7cdb0a66bc6f123dcf9617f67d7dce3b3d99bbb1fdad64R265-R266 which was merged after this PR was created.

You could refer https://github.com/luixxiul/matrix-react-sdk/commit/72fd5215db88ef839a8c815761f5f3a3ea58ae86 if you are still interested, since I don't want to hijack the PR.

**Pull request closed without merging**
