### PR TITLE
Enable new room UI by default on `develop.element.io`

### PR DESCRIPTION
**Pull request by germain-gg**
As discussed with @Johennes and @daniellekirkwood 

## Checklist

-   [ ] Tests written for new code (and old code if feasible)
-   [ ] Linter and other CI checks pass
-   [ ] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/vector-im/element-web/blob/develop/CONTRIBUTING.md))

Fixes: https://github.com/vector-im/element-web/issues/26116

---
This change is marked as an *internal change* (Task), so will not be included in the changelog.

### CODE REVIEW

**Comment by t3chguy** [comment]
Blocked by https://github.com/vector-im/element-web/issues/26090

**Review by richvdh — APPROVED** [review]

**Comment by andybalaam** [comment]
Pausing this for now - some more work is needed first.

**Comment by t3chguy** [comment]
Also blocked by https://github.com/vector-im/element-web/issues/26105

**Comment by Johennes** [comment]
https://github.com/vector-im/element-web/issues/26105 has been fixed and https://github.com/vector-im/element-web/issues/26090 only strikes when the knocking labs flag is turned on now. Other MVP room header issues have also been fixed. So this seems ready to go ahead now.

**Pull request merged**
