### PR TITLE
Remove docs for `feature_hidden_read_receipts`

### PR DESCRIPTION
**Pull request by SimonBrandner**
Requires https://github.com/matrix-org/matrix-react-sdk/pull/9128

---
This change is marked as an *internal change* (Task), so will not be included in the changelog.

### CODE REVIEW

**Review by turt2live — CHANGES_REQUESTED** [review]
Title != implementation

**Comment by SimonBrandner** [comment]
> Title != implementation

Haha, let's pretend that did not happen

**Review by turt2live — APPROVED** [review]

**Review by turt2live — APPROVED** [review]
lgtm, fwiw :)

(pretty sure this isn't supposed to be a draft?)

**Comment by boontifex** [comment]
Hello,
we are seaching for the config.json option to disable sendReadReceipts per default, is this available?

**Comment by SimonBrandner** [comment]
> Hello, we are seaching for the config.json option to disable sendReadReceipts per default, is this available?

Hi, no, we don't have that atm, I would suggest you open an issue for this feature

**Pull request merged**
