### PR TITLE
Cease uploading develop.tar.gz to Github Pages

### PR DESCRIPTION
**Pull request by t3chguy**
Requires https://github.com/vector-im/element-desktop/pull/450
The branch can then also be cleaned up

---
This change is marked as an *internal change* (Task), so will not be included in the changelog.

### CODE REVIEW

**Review by richvdh — COMMENTED** [review]
should we leave this in place for a few days/weeks to give everyone a change to fetch the latest version?

**Comment by t3chguy** [comment]
Arguably no, it makes all git operations slower due to the large tarball
This tarball is only really used for the Nightly builder, https://github.com/vector-im/element-desktop/#fetching-element doesn't officially support fetching develop builds and anyone inherently using it just needs to update their develop element-desktop repo

**Comment by t3chguy** [comment]
Arguably no, it makes all git operations slower due to the large tarball
This tarball is only really used for the Nightly builder, https://github.com/vector-im/element-desktop/#fetching-element doesn't officially support fetching develop builds and anyone inherently using it just needs to update their develop element-desktop repo

**Comment by richvdh** [comment]
ok I think I need to understand where fetch-package.js is used.

I would read the comments in that file to find out, but, well...

**Comment by richvdh** [comment]
Oh I see, it's https://github.com/vector-im/element-desktop/blob/develop/package.json#L19

ok, sgtm then

**Review by richvdh — APPROVED** [review]

**Pull request merged**
