### PR TITLE
Document Bridge Error feature

### PR DESCRIPTION
**Pull request by V02460**
Signed-off-by: Kai A. Hiller <KaiAlexHiller@web.de>

### CODE REVIEW

**Comment by jryans** [comment]
@turt2live What's the status of this feature? Should we still attempt to merge this PR?

**Comment by turt2live** [comment]
I'm not sure of the status. @V02460 or @Half-Shot might know.

**Comment by Half-Shot** [comment]
Not yet, we're likely going to take a second look at the MSC which is going to change quite a bit.

**Comment by Palid** [comment]
@Half-Shot is this still relevant?

**Comment by Half-Shot** [comment]
Closing, the linked PR isn't being worked on.

**Pull request closed without merging**
