### PR TITLE
Update README.md

### LINKED ISSUE #16555: Single layer build instructions possibly broken
Some people are reporting that `yarn install` followed by `yarn dist` in the main repo alone (without the other 2 layers) fails with the error:

```
Module not found: Error: Can't resolve './component-index' in '/home/eiko/Coding/git/element-web/node_modules/matrix-react-sdk/src'
```

Since this is one of the setup paths we [describe in the docs](https://github.com/vector-im/element-web#building-from-source), we should either fix this or remove this path from the docs.

### PR DESCRIPTION
**Pull request by barrowsys**
Related to #16555

Signed-off-by: Ezra Barrow <barrow@tilde.team>

### CODE REVIEW

**Comment by SimonBrandner** [comment]
Nice, thanks! Though I don't think we'd consider this fixing the issue, it would probably be better to fix the problem itself, though changing the README would great for now

**Comment by psrpinto** [comment]
I just stumbled upon this issue.

> it would probably be better to fix the problem itself

I'm not familiar with the root cause of this, but if currently `yarn reskindex` is a required step, I think it should be documented in the setup instructions.

**Comment by SimonBrandner** [comment]
> I just stumbled upon this issue.
> 
> > it would probably be better to fix the problem itself
> 
> I'm not familiar with the root cause of this, but if currently `yarn reskindex` is a required step, I think it should be documented in the setup instructions.

Yeah, I completely agree, I just don't think we should close that issue after updating the README - could you please remove the _Fixes..._ part from the description

**Review by jryans — APPROVED** [review]
Thanks, let's add it for now. I edited the top comment so it won't close the issue, as there's hopefully a more permanent fix.

**Pull request merged**
