### PR TITLE
Create a screenshots page that will allow us to do screenshot testing

### PR DESCRIPTION
**Pull request by andybalaam**
As discussed quite a while ago, our [CONTRIBUTING](https://github.com/matrix-org/matrix-js-sdk/blob/develop/CONTRIBUTING.md#tests) guide mentions screenshot tests, but we don't have a way of doing that yet.

This adds a page called screenshots.html that renders fixed versions of different components when we choose them.

Future work in matrix-react-sdk will allow us to:
* create PNG screenshots of each component on screenshots.html
* compare them with references

---
This change is marked as an *internal change* (Task), so will not be included in the changelog.

### CODE REVIEW

**Comment by turt2live** [comment]
should this be at this level, or in the react-sdk?

**Comment by andybalaam** [comment]
> should this be at this level, or in the react-sdk?

I could not see how to do this (make a new page like this) in react-sdk.  If you can point me in the right direction, I'd be happy to do that.

**Comment by turt2live** [comment]
it'll almost certainly require infrastructure to be created to support it, but ultimately we're not testing Element we're testing the React SDK, so should be somewhere in there.

**Comment by andybalaam** [comment]
> it'll almost certainly require infrastructure to be created to support it, but ultimately we're not testing Element we're testing the React SDK, so should be somewhere in there.

OK, closing this PR so I can work on one in matrix-react-sdk

**Pull request closed without merging**
