### PR TITLE
Implement maySendNotifications based upon do-not-disturb work

### PR DESCRIPTION
**Pull request by Half-Shot**
This is paired with https://github.com/vector-im/element-desktop/pull/133 and https://github.com/matrix-org/matrix-react-sdk/pull/5097

### CODE REVIEW

**Comment by Half-Shot** [comment]
Linter errors are due to the change in types for `BasePlatform`

**Comment by nadonomy** [comment]
@Half-Shot @t3chguy I have a review request on this but there's not enough context for me to review or input in any meaningful way. Is it worth expanding to provide that context, or continue without needing approval for this set of changes?

**Comment by t3chguy** [comment]
As a product do we want to try and honor platform do-not-disturb for a very small subset of platforms (Linux with Gnome but only in a subset of installations) @nadonomy

**Comment by Half-Shot** [comment]
@nadonomy The context is this change would change Element so that it will mute notifications (and hide them) if the operating system was placed in a Do Not Disturb mode (usually toggled in the notification area of the OS).

Let me know if you want more info, or can approve without?

**Comment by jryans** [comment]
I'd like to get a Product call on this before proceeding with code review. Removing from queue for now.

**Comment by nadonomy** [comment]
Hey @Half-Shot @jryans we had a discussion on this during a Notifications sync. After discussing in detail, we concluded:

1. Any implementation would be orthogonal to the current notifications (re)work so there's little risk of us double handling this, or needing to block this on the other work landing
2. There's concern over swallowing the entire notifications (as opposed to just muting). Our suspicion is some Linux notification daemons would prefer to still receive notifications, to triage & allow users to review. Is there anything smarter we can do?

**Comment by Half-Shot** [comment]
>There's concern over swallowing the entire notifications (as opposed to just muting). Our suspicion is some Linux notification daemons would prefer to still receive notifications, to triage & allow users to review. Is there anything smarter we can do?

This was the case but I have since fixed it.

**Comment by Half-Shot** [comment]
The tests seem to be failing due to something unrelated to my change.

**Review by turt2live — CHANGES_REQUESTED** [review]
positive intent please (see react-sdk)

**Comment by turt2live** [comment]
@Half-Shot is this still on your radar?

**Comment by Half-Shot** [comment]
In the end, this became a bit of a burden to work on. I don't actually use a platform that supports DND anymore, so this change isn't going to be completed by me.

**Pull request closed without merging**
